### ISSUE TITLE
Allow using different download_dir for lightkurve

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#13]
Hi, since the recent addition of Lightkurve for Kepler and K2 I've noticed that TRICERATOPS now stores the Lightkurve caches in the default home directory the fits files. I'd like to suggest a pull request to merge a change where the Triceratops constructor will receive the lightkurve_cache_dir so it can be passed to the Lightkurve `download_all` methods. That way the place where the caches are loaded and stored will be customizable.

Is there any other place in Triceratops where Lightkurve (or Eleanor, for instance) is used?

If this is ok for you I will do it.

Regards.

**Comment by stevengiacalone** [comment]
Absolutely, go right ahead! Thanks for offering to make that update.
