### ISSUE TITLE
[Bug] Error when kepler target not in catalog

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#24]
Hello, for some reason there are some KIC that are not in the Vizier `J/ApJS/229/30/catalog` catalog used by TRICERATOPS and this causes an error that aborts the execution of the code. E.g. KIC 2569583. As this catalog and the K2 ones are only used to retrieve `ra` and `dec`, I'd like to ask for the option to introduce both values in the TRICERATOPS `target` constructor. That way we could skip using those catalogs if we already knew the celestial coordinates.

Regards.

**Comment by stevengiacalone** [comment]
Great idea! I'll add that option and push a new version to pypi next time I get the chance.
