### ISSUE TITLE
Pytransit issues

### ISSUE THREAD

**Issue by Codeiology** [stevengiacalone/triceratops#28]
I followed the instructions and created a new conda environment with python=3.8, but I get the following error when I try to import it to my project .IPYNB:
`ModuleNotFoundError: No module named 'pytransit.models.roadrunner.opmodel'`
I am running github codespace posix because it also showed the same error on my M1 macbook air. Is there any way to fix this that doesnt require editing the src?

**Comment by exo-pt** [comment]
Hi,

After upgrading PyTransit to 2.6.3, I had today the same error when importing QuadraticModel
    from pytransit import QuadraticModel

After downgrading to PyTransit==2.6.1 the error was gone.
Hope this helps...

**Comment by hpparvi** [comment]
Thanks, this should be fixed now in PyTransit 2.6.4. Can you try upgrading PyTransit. 

I recently changed the way the packaging configuration is done (from setup.py to pyproject.toml), and while this doesn't seem to cause any issues with Python >= 3.9, something went wrong with Python 3.8.

**Comment by exo-pt** [comment]
Yes, the error is gone with v2.6.4
I forgot to say that I was also working with a 3.8 Python version.

Thanks
Rafael

**Comment by Codeiology** [comment]
Thanks so much, the update works and the error is mitigated.

**Comment by stevengiacalone** [comment]
Thanks for taking care of that, @hpparvi !
