### ISSUE TITLE
Target.plot_fits not returning figure

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#3]
Hi,

I'd like to be able to save the generated image when using target.plot_fits. However, plt.show() is called at the end of the method and the figure is not returning. Therefore I'm unable to save the figure, which would be needed when running headless (in a server, for instance). Is here any way I can do it right now or does the code need to be changed a little bit?

Kind regards.

**Comment by stevengiacalone** [comment]
I've included an option to save the figures generated by plot_field and plot_fits as pdfs in the latest update. To do so, set "save=True" as an argument. You can also designate your own name for the pdf using the "fname" argument. Let me know if this doesn't resolved the issue.

**Comment by martindevora** [comment]
It seems enough to me. Thank you!
