### ISSUE TITLE
v1.0.8 returns empty probs when Ms < 0.1

### ISSUE THREAD

**Issue by martindevora** [stevengiacalone/triceratops#5]
Hi, after version 1.0.8 was released (Ms < 0.1 is allowed now) the execution is still working for "standard" scenarios. However, even though it now works when there are stars lacking of Mass or Radius info, now the final probability results are empty. I'm attaching a jupyter notebook together with the light curve that it uses to prove my proceedings.

[example.zip](https://github.com/stevengiacalone/triceratops/files/6343889/example.zip)

Kind regards and thank you in advance.

**Comment by stevengiacalone** [comment]
The reason for the NaNs in probability field seems to be that the nearby star (TIC 29781293) is still missing a mass. The latest version of the code should automatically fill this in with a Solar mass, but that doesn't appear to be happening. That said, I'm not sure triceratops correctly updated to v1.0.8 before you ran the notebook you provided. There are a few changes that should have done the following:
- The target.stars table should now include the 2MASS (JHK) magnitudes
- target.calc_depths should print a warning about TIC 29781293 missing a mass

Can you confirm that you're running v1.0.8? If you are, there is probably another issue I'm not catching.

**Comment by martindevora** [comment]
Sorry my mistake. Here you have the notebook run with python 3.8 and triceratops 1.0.8 (still no warning message tho, but I can see it when running out of the notebook in console).
[example.zip](https://github.com/stevengiacalone/triceratops/files/6345707/example.zip)

**Comment by stevengiacalone** [comment]
No problem! I went through the new notebook and it looks like the changes are working correctly. The warning appears directly below the cell where target.calc_depths() is run (before the target.stars table). The nearby star TIC 29781293 is also correctly being assigned a Solar mass when target.calc_probs() is run (which can be seen in the target.probs table at the end of the notebook).

The reason for the NaN seems to be the light curve being entered into target.calc_probs(). With the current code, the data points don't cover the entire transit (along the time axis) and the value for sigma is NaN. I recommend replacing the cell that folds and masks the light curve with the following:
```
# read in the light curve
lc = pd.read_csv("TOI282_lightcurve.csv", header=None)
time, flux, flux_err = lc[0].values, lc[1].values, lc[2].values
P_orb = 56.0091
duration = 490.81 / 60 / 24
epoch = 1337.20

lc = TessLightCurve(time, flux, flux_err)
lc = lc.fold(period=P_orb, t0=epoch)
folded_plot_range = duration + 0.1
inner_folded_range_args = np.where((0 - folded_plot_range < lc.time) & (lc.time < 0 + folded_plot_range))
lc = lc[inner_folded_range_args]
lc = lc.bin(0.005)
sigma = np.mean(lc.flux_err.value)
plt.errorbar(lc.time.value, lc.flux.value, lc.flux_err.value, fmt='k.');
```

This should resolve the issue and allow the calculation to return a non-NaN FPP.

**Comment by martindevora** [comment]
Hi. Sorry that happened because I mixed your notebook with my pipeline's code. Here I attach it again, plotting the selected lightcurve frame, using a proper value of sigma and still NaN values are found in the probabilities and scenarios.

[example.zip](https://github.com/stevengiacalone/triceratops/files/6357972/example.zip)

Thanks for keeping helping with this.

**Comment by stevengiacalone** [comment]
In this case it looks like the time data being entered in target.calc_probs() is in units of orbital phase, rather than the required units of days. Lightkurve sometimes switches between the two based on the arguments in their functions. The code is returning NaN probabilities because it's trying to fit the light curve model to a transit with a duration that is 56x shorter than it should be, so the fit essentially fails ever time. Multiplying your time data by the orbital period should solve the issue.

**Comment by martindevora** [comment]
Thats true. It happened again that I forgot to move a line of code from my custom code to the notebook. Now I multiplied it by the orbital period. Despite, the same values I'm encountering.

[example.zip](https://github.com/stevengiacalone/triceratops/files/6373049/example.zip)

Again thanks for your help. Please let me know whether you find anything else to be corrected. Kind regards.

**Comment by stevengiacalone** [comment]
Everything looks good now, but the code is running into an issue that I've yet to resolve. The code sometimes returns NaN when there are too many data points entered into target.calc_probs(). Binning the phase-folded light curve a little bit should fix this for you (I used a binsize of 20). I'll try to come up with a more permanent fix for this in the near future.

**Comment by martindevora** [comment]
Ok. I've already tried to bin the curve and now the probabilities appear to be correctly extracted, even though it'd be preferable to use the original curve. I will apply this workaround into my code.

Thank you very much.
